# 開発環境を構築する
#
#

# nginx-proxy
proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro

# jenkins container
jenkins:
  image: jenkinsci/jenkins:2.9
  volumes_from:
    - jenkins_data
  ports:
#    - "8080:8080"
    - "50000:50000"
  environment:
    - VIRTUAL_HOST=jenkins.dev
    - VIRTUAL_PORT=8080
#  links:
#    - gitbucket:gitbucket.dev
#    - nexus:nexus.dev
#    - sonarqube:sonar.dev
#    - redmine:redmine.dev
#    - tomcat:tomcat.dev
  extra_hosts:
    - "redmine.dev jenkins.dev sonar.dev gitbucket.dev nexus.dev jenkins.order.dev sonar.order.dev alminium.order.dev mail.test.dev:10.193.68.22"

# jenkins data volume container
jenkins_data:
  image: jenkinsci/jenkins:2.9
  command: echo "jenkins data volume container."

# sonatype nexus container
nexus:
  image: sonatype/nexus:oss
  environment:
    - MAX_HEAP=512m
  volumes_from:
    - nexus_data
  environment:
    - VIRTUAL_HOST=nexus.dev
    - VIRTUAL_PORT=8081

# nexus data valume container 
nexus_data:
  image: sonatype/nexus:oss
  command: echo "data-only container for Nexus"

# gitbucket container
gitbucket:
  image: f99aq8ove/gitbucket:3.14
  volumes_from:
    - gitbucket_data
  ports:
    - "29418:29418"
  environment:
    - VIRTUAL_HOST=gitbucket.dev
    - VIRTUAL_PORT=8080

# gitbucket data value container
gitbucket_data:
  image: f99aq8ove/gitbucket:3.14
  command: echo "data-only container for gitbucket"

# mysql container
mysql:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=hogehoge
  ports:
    - "3306:3306"
  volumes_from:
    - mysql_data

# mysql container
mysql_data:
  image: mysql
  command: echo "mysql data volume container."

# sonarqube container
sonarqube:
  image: sonarqube:5.6
  environment:
    - VIRTUAL_HOST=sonar.dev
    - VIRTUAL_PORT=9000
    - SONARQUBE_JDBC_USERNAME=sonar
    - SONARQUBE_JDBC_PASSWORD=sonar
    - SONARQUBE_JDBC_URL=jdbc:mysql://mysql/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
  links:
    - mysql:mysql
  volumes_from:
    - sonarqube_data
  ports:
    - "9000:9000"

# sonarqube data volume container
sonarqube_data:
  image: sonarqube:5.6
  command: echo "sonarqube data volume container."

# redmine container
redmine:
  image: redmine:3.0.7
  links:
    - mysql:mysql
  volumes_from:
    - redmine_data
  environment:
    - VIRTUAL_HOST=redmine.dev
    - VIRTUAL_PORT=3000
    - REDMINE_NO_DB_MIGRATE=true

# redmine data valume container
redmine_data:
  image: redmine:3.0.7
  command: echo "data-only container for redmine"
