# 開発環境を構築する
#
#

# nginx-proxy
proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro

# jenkins container
jenkins:
  image: jenkins
  volumes_from:
    - jenkins_data
#  ports:
#    - "8080:8080"
  environment:
    - VIRTUAL_HOST=jenkins.dev
    - VIRTUAL_PORT=8080
  links:
    - gitbucket:gitbucket.dev
    - nexus:nexus.dev
    - sonarqube:sonar.dev
    - redmine:redmine.dev
    - tomcat:tomcat.dev
#  extra_hosts:


# jenkins data volume container
jenkins_data:
  image: jenkins
  command: echo "jenkins data volume container."

# sonatype nexus container
nexus:
  image: sonatype/nexus:oss
  environment:
    - MAX_HEAP=512m
  volumes_from:
    - nexus_data
  environment:
    - VIRTUAL_HOST=nexus.dev
    - VIRTUAL_PORT=8081

# nexus data valume container 
nexus_data:
  image: sonatype/nexus:oss
  command: echo "data-only container for Nexus"

# gitbucket container
gitbucket:
  image: f99aq8ove/gitbucket
  volumes_from:
    - gitbucket_data
  ports:
    - "29418:29418"
  environment:
    - VIRTUAL_HOST=gitbucket.dev
    - VIRTUAL_PORT=8080

# gitbucket data value container
gitbucket_data:
  image: f99aq8ove/gitbucket
  command: echo "data-only container for redmine"

# mysql container
mysql:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=hogehoge
  ports:
    - "3306:3306"
  volumes_from:
    - mysql_data

# mysql container
mysql_data:
  image: mysql
  command: echo "sonarqube data volume container."

# sonarqube container
sonarqube:
  image: sonarqube
  environment:
    - VIRTUAL_HOST=sonar.dev
    - VIRTUAL_PORT=9000
    - SONARQUBE_JDBC_USERNAME=sonar
    - SONARQUBE_JDBC_PASSWORD=sonar
    - SONARQUBE_JDBC_URL=jdbc:mysql://mysql/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
  links:
    - mysql:mysql
  volumes_from:
    - sonarqube_data

# sonarqube data volume container
sonarqube_data:
  image: sonarqube
  command: echo "sonarqube data volume container."

# redmine container
redmine:
  image: redmine
  links:
    - mysql:mysql
  volumes_from:
    - redmine_data
  environment:
    - VIRTUAL_HOST=redmine.dev
    - VIRTUAL_PORT=3000

# redmine data valume container
redmine_data:
  image: redmine
  command: echo "data-only container for redmine"

# selenium hub container
selenium-hub:
  image: selenium/hub
  ports:
    - "4444:4444"

# selenium node chrome container
selenium-chrome:
  image: selenium/node-chrome-debug
  ports:
    - "5900:5900"
  links:
    - selenium-hub:hub

# selenium node firefox container
selenium-firefox:
  image: selenium/node-firefox-debug
  ports:
    - "5901:5900"
  links:
    - selenium-hub:hub

# glassfish
glassfish:
  image: glassfish
  ports:
#    - "14848:4848"
    - "18080:8080"
    - "18181:8181"
  environment:
    - VIRTUAL_HOST=glassfish.dev
    - VIRTUAL_PORT=4848

# tomcat container
tomcat:
  image: tomcat:jre8
  environment:
    - VIRTUAL_HOST=tomcat.dev
    - VIRTUAL_PORT=8080
