# 開発環境を構築する
#
#

# nginx-proxy
proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro

# jenkins container
jenkins:
  image: jenkins
  volumes_from:
    - jenkins_data
#  ports:
#    - "8080:8080"
  environment:
    - VIRTUAL_HOST=jenkins.hagi.home
    - VIRTUAL_PORT=8080
  links:
    - gitbucket:gitbucket.hagi.home
    - nexus:nexus.hagi.home
    - sonarqube:sonar.hagi.home
    - redmine:redmine.hagi.home
#  extra_hosts:


# jenkins data volume container
jenkins_data:
  image: jenkins
  command: echo "jenkins data volume container."

# sonatype nexus container
nexus:
  image: sonatype/nexus:oss
  environment:
    - MAX_HEAP=512m
  volumes_from:
    - nexus_data
  environment:
    - VIRTUAL_HOST=nexus.hagi.home
    - VIRTUAL_PORT=8081

# nexus data valume container 
nexus_data:
  image: sonatype/nexus:oss
  command: echo "data-only container for Nexus"

# gitbucket container
gitbucket:
  image: f99aq8ove/gitbucket
  volumes_from:
    - gitbucket_data
  ports:
    - "29418:29418"
  environment:
    - VIRTUAL_HOST=gitbucket.hagi.home
    - VIRTUAL_PORT=8080

# gitbucket data value container
gitbucket_data:
  image: f99aq8ove/gitbucket
  command: echo "data-only container for redmine"

# mysql container
mysql:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=hogehoge
  ports:
    - "3306:3306"
  volumes_from:
    - mysql_data

# mysql container
mysql_data:
  image: mysql
  command: echo "sonarqube data volume container."

# sonarqube container
sonarqube:
  image: sonarqube
  environment:
    - VIRTUAL_HOST=sonar.hagi.home
    - VIRTUAL_PORT=9000
    - SONARQUBE_JDBC_USERNAME=sonar
    - SONARQUBE_JDBC_PASSWORD=sonar
    - SONARQUBE_JDBC_URL=jdbc:mysql://mysql/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
  links:
    - mysql:mysql
  volumes_from:
    - sonarqube_data

# sonarqube data volume container
sonarqube_data:
  image: sonarqube
  command: echo "sonarqube data volume container."

# redmine container
redmine:
  image: redmine
  links:
    - mysql:mysql
  volumes_from:
    - redmine_data
  environment:
    - VIRTUAL_HOST=redmine.hagi.home
    - VIRTUAL_PORT=3000

# redmine data valume container
redmine_data:
  image: redmine
  command: echo "data-only container for redmine"

# mailserver
mailserver:
  image: tvial/docker-mailserver
  hostname: mail
  domainname: hagi.home
  ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
  volumes:
    - ./spamassassin:/tmp/spamassassin/
    - ./postfix/:/tmp/postfix/
  #volumes-from:
  #  - mail_data

# mailserver data
#mailserver_data:
#  image: tvial/docker-mailserver
#  command: echo "data-only container for mail"

