# 開発環境を構築する
version: "3.0"

services:

  # nginx-proxy
  proxy:
    build: proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  # jenkins container
  jenkins:
    build: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - VIRTUAL_HOST=jenkins.dev
      - VIRTUAL_PORT=8080
    extra_hosts:
      - "redmine.dev jenkins.dev sonar.dev gitbucket.dev nexus.dev:10.193.68.22"
      - "sonar.order.dev alminium.order.dev:10.193.68.22"
      - "alminium.mam.dev:10.193.68.22"
      - "mail.test.dev:10.193.68.22"

  # sonatype nexus container
  nexus:
    image: sonatype/nexus:2.13.0-01
    environment:
      - MAX_HEAP=512m
    volumes:
      - sonatype_work:/sonatype-work
    environment:
      - VIRTUAL_HOST=nexus.dev
      - VIRTUAL_PORT=8081
    ports:
      - "18081:8081"

  # gitbucket container
  gitbucket:
    image: f99aq8ove/gitbucket:3.14
    volumes:
      - gitbucket_data:/gitbucket
    ports:
      - "29418:29418"
    environment:
      - VIRTUAL_HOST=gitbucket.dev
      - VIRTUAL_PORT=8080

  # mysql container
  mysql:
    image: mysql:5.7.14
    environment:
      - MYSQL_ROOT_PASSWORD=hogehoge
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # sonarqube container
  sonarqube:
    image: sonarqube:5.6
    environment:
      - VIRTUAL_HOST=sonar.dev
      - VIRTUAL_PORT=9000
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:mysql://mysql/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
    links:
      - mysql:mysql
    volumes:
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_data:/opt/sonarqube/data
    ports:
      - "9000:9000"

  # redmine container
  redmine:
    image: redmine:3.0.7
    links:
      - mysql:mysql
    volumes:
      - redmine_data:/usr/src/redmine/files
    environment:
      - VIRTUAL_HOST=redmine.dev
      - VIRTUAL_PORT=3000

volumes:
  jenkins_home:
  sonatype_work:
  gitbucket_data:
  mysql_data:
  sonarqube_extensions:
  sonarqube_data:
  redmine_data:
